apiVersion: v1
kind: Service
metadata:
  name: jenkins-manual
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-manual
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins